### ISSUE TITLE
SunRise and Sunset Methods Flip To Next Day After SunSet Time Passes

### ISSUE THREAD

**Issue by jaycollett** [sfrwmaker/sunMoon#2]
Not sure if this is by design or not but when the time passes the time of the calculated sunset, calls to sunrise and sunset return the next day's rise and set. Shouldn't the calls stick to the current day's sunrise and sunset until 24:59:59 (midnight)?

This is reproducible if you have your RTC set to UTC time and provide the sm.init call your offset and long and latitude. I've even validated that providing a t_time value to the sunRise() and sunSet() calls for a past date/time gives me tomorrow's sunrise and sunset. I'm using a -240 min offset with the init.

**Comment by sfrwmaker** [comment]
Look, the first thing the method sunTime does, it calculates the day of the year. If the offset is negative, you could get 'tomorrow' day. The method assumes you pass it localtime, not UTC.
I could add couple of the methods in case you supply the UTC time if you wish. Would thishelp?

time_t sunMoon::sunTime(bool sunRise, time_t date) {

  if (date == 0) date = now();
  date -= tz*60;

**Comment by jaycollett** [comment]
I think I've eliminated a lot of the variables at play with the issue I'm having. I have found that if I create the SunnMoon obj and pass today's local time I get the correct sunrise and sunset for today until after the calculated sunset. If I run the same code again after the sunset time, I get the next day's sunrise and sunset. The code below will work fine until the calculated sunset for today.

```
sm.init(-240, 40.712784, -74.005941);

tmElements_t  tm;                             // specific time hardcoded date/time for TODAY

  tm.Second = 0;
  tm.Minute = 12;
  tm.Hour   = 12;
  tm.Day    = 29;
  tm.Month  = 3;
  tm.Year   = 2017 - 1970;
  time_t s_date = makeTime(tm);

  time_t sRise = sm.sunRise(s_date);
  time_t sSet  = sm.sunSet(s_date);

  Serial.print("Today sunrise and sunset: ");
  printDate(sRise); Serial.print("; ");
  printDate(sSet);  Serial.println("");
```

**Comment by sfrwmaker** [comment]
Hello!

Thank you very much for issue reported.

First, i have fixed one bug in the sunMoon::sunTime. The problem was concerned with 'day of the year'  calculation (integer). Now it calculated for noon time of the date specified by the parameter date.
For your timezone the output listing is the following:
Today sunrise and sunset: 12:42 29-03-2017:  6:43 29-03-2017; 19:18 29-03-2017
...
Today sunrise and sunset: 22:12 29-03-2017:  6:43 29-03-2017; 19:18 29-03-2017
Today sunrise and sunset: 22:42 29-03-2017:  6:43 29-03-2017; 19:18 29-03-2017
Today sunrise and sunset: 23:12 29-03-2017:  6:43 29-03-2017; 19:18 29-03-2017
Today sunrise and sunset: 23:42 29-03-2017:  6:43 29-03-2017; 19:18 29-03-2017
Today sunrise and sunset:  0:12 30-03-2017:  6:41 30-03-2017; 19:19 30-03-2017
Today sunrise and sunset:  0:42 30-03-2017:  6:41 30-03-2017; 19:19 30-03-2017
Today sunrise and sunset:  1:12 30-03-2017:  6:41 30-03-2017; 19:19 30-03-2017
Today sunrise and sunset:  1:42 30-03-2017:  6:41 30-03-2017; 19:19 30-03-2017
The first data is the parameter passed into the sunRise or sunSet functions.

**Comment by jaycollett** [comment]
Awesome, I'm out of town for the next week but when I return I'll validate in my sketch and close the issue! Again, awesome library and awesome communication!

**Comment by jaycollett** [comment]
This indeed fixed the issue and I verified with multiple tests. Thanks for the quick fix!
